name: CPFix
main: fromgate.cpfix.CPFix
version: 0.2.0
author: fromgate, fromgate@gmail.com
commands:
   cpfix:
      description: Show settings of plugin (or reloads configuration)
      usage: |
           /cpfix [reload]